
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141204 (SVN rev 60)
//----------------------------------------------------

package cup.example;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int h2Close = 145;
  public static final int liClose = 113;
  public static final int iOpen = 118;
  public static final int dlClose = 166;
  public static final int preOpen = 187;
  public static final int legendClose = 175;
  public static final int h6Close = 154;
  public static final int h3Open = 146;
  public static final int delClose = 197;
  public static final int pOpen = 116;
  public static final int smallOpen = 132;
  public static final int BVAL = 12;
  public static final int sClose = 67;
  public static final int bigClose = 127;
  public static final int dtClose = 168;
  public static final int RPAREN = 8;
  public static final int varClose = 53;
  public static final int addressClose = 25;
  public static final int framesetClose = 87;
  public static final int TIMES = 6;
  public static final int layerOpen = 200;
  public static final int strikeClose = 71;
  public static final int framesetOpen = 86;
  public static final int insClose = 199;
  public static final int WBR = 30;
  public static final int legendOpen = 174;
  public static final int divisionOpen = 157;
  public static final int basefontOpen = 76;
  public static final int noembedClose = 57;
  public static final int textareaClose = 178;
  public static final int UMINUS = 5;
  public static final int trClose = 100;
  public static final int KEYGEN = 171;
  public static final int kbdClose = 47;
  public static final int ddOpen = 169;
  public static final int multicolClose = 186;
  public static final int h6Open = 153;
  public static final int sOpen = 66;
  public static final int thOpen = 103;
  public static final int codeOpen = 40;
  public static final int emClose = 45;
  public static final int insOpen = 198;
  public static final int supClose = 135;
  public static final int fieldsetOpen = 172;
  public static final int bdoClose = 63;
  public static final int h3Close = 147;
  public static final int scriptClose = 23;
  public static final int optionOpen = 95;
  public static final int LABEL = 176;
  public static final int listingClose = 182;
  public static final int aOpen = 108;
  public static final int hr = 155;
  public static final int layerClose = 201;
  public static final int kbdOpen = 46;
  public static final int pClose = 117;
  public static final int bodyOpen = 83;
  public static final int thead = 148;
  public static final int EOF = 0;
  public static final int COL = 192;
  public static final int MINUS = 4;
  public static final int blockquoteClose = 79;
  public static final int objectClose = 61;
  public static final int marqueeClose = 75;
  public static final int IFRAME = 27;
  public static final int headClose = 162;
  public static final int BASE = 14;
  public static final int dirOpen = 80;
  public static final int PARAM = 31;
  public static final int h2Open = 144;
  public static final int ilayerClose = 55;
  public static final int nobrOpen = 126;
  public static final int tdOpen = 101;
  public static final int ulOpen = 110;
  public static final int semicolon = 124;
  public static final int appletOpen = 32;
  public static final int COLGROUP = 191;
  public static final int optionClose = 96;
  public static final int trOpen = 99;
  public static final int scriptOpen = 22;
  public static final int NUMBER = 9;
  public static final int assign = 125;
  public static final int xmpOpen = 194;
  public static final int strongClose = 51;
  public static final int aClose = 109;
  public static final int acronymOpen = 36;
  public static final int IMG = 28;
  public static final int fontOpen = 140;
  public static final int formOpen = 90;
  public static final int input = 92;
  public static final int SEMI = 2;
  public static final int textareaOpen = 177;
  public static final int fontClose = 141;
  public static final int fieldsetClose = 173;
  public static final int headOpen = 161;
  public static final int noembedOpen = 56;
  public static final int citeOpen = 38;
  public static final int img = 107;
  public static final int noframesOpen = 88;
  public static final int bigOpen = 128;
  public static final int iClose = 119;
  public static final int captionOpen = 189;
  public static final int dirClose = 81;
  public static final int h5Open = 151;
  public static final int menuOpen = 183;
  public static final int h4Close = 150;
  public static final int subOpen = 136;
  public static final int RVAL = 11;
  public static final int selectClose = 94;
  public static final int htmlClose = 160;
  public static final int acronymClose = 37;
  public static final int PLUS = 3;
  public static final int LPAREN = 7;
  public static final int qClose = 49;
  public static final int captionClose = 190;
  public static final int optgroupClose = 180;
  public static final int frameOpen = 85;
  public static final int comma = 123;
  public static final int tdClose = 102;
  public static final int preClose = 188;
  public static final int IVAL = 10;
  public static final int supOpen = 134;
  public static final int AREA = 204;
  public static final int uClose = 121;
  public static final int dfnClose = 43;
  public static final int mapOpen = 202;
  public static final int META = 17;
  public static final int ilayerOpen = 54;
  public static final int styleClose = 20;
  public static final int tfoot = 193;
  public static final int formClose = 91;
  public static final int subClose = 137;
  public static final int tableClose = 98;
  public static final int thClose = 104;
  public static final int tbody = 106;
  public static final int noscriptOpen = 58;
  public static final int titleClose = 164;
  public static final int h1Open = 142;
  public static final int appletClose = 33;
  public static final int ISINDEX = 15;
  public static final int comment = 206;
  public static final int plainText = 21;
  public static final int uOpen = 120;
  public static final int styleOpen = 19;
  public static final int ulClose = 111;
  public static final int citeClose = 39;
  public static final int basefontClose = 77;
  public static final int dfnOpen = 42;
  public static final int bClose = 131;
  public static final int bodyClose = 84;
  public static final int listingOpen = 181;
  public static final int dtOpen = 167;
  public static final int ttClose = 73;
  public static final int titleOpen = 163;
  public static final int tableOpen = 97;
  public static final int abbrClose = 35;
  public static final int abbrOpen = 34;
  public static final int spanOpen = 68;
  public static final int marqueeOpen = 74;
  public static final int centerOpen = 138;
  public static final int olClose = 115;
  public static final int thread = 105;
  public static final int h1Close = 143;
  public static final int BGSOUND = 13;
  public static final int noscriptClose = 59;
  public static final int spanClose = 69;
  public static final int h4Open = 149;
  public static final int br = 156;
  public static final int qOpen = 48;
  public static final int h5Close = 152;
  public static final int endTag = 82;
  public static final int olOpen = 114;
  public static final int optgroupOpen = 179;
  public static final int LINK = 16;
  public static final int varOpen = 52;
  public static final int blinkOpen = 64;
  public static final int ttOpen = 72;
  public static final int nobrClose = 129;
  public static final int NEXTID = 18;
  public static final int strikeOpen = 70;
  public static final int whitespace = 207;
  public static final int codeClose = 41;
  public static final int addressOpen = 24;
  public static final int mapClose = 203;
  public static final int liOpen = 112;
  public static final int EMBED = 26;
  public static final int colon = 122;
  public static final int blockquoteOpen = 78;
  public static final int error = 1;
  public static final int ID = 205;
  public static final int emOpen = 44;
  public static final int divisionClose = 158;
  public static final int bdoOpen = 62;
  public static final int smallClose = 133;
  public static final int noframesClose = 89;
  public static final int dlOpen = 165;
  public static final int selectOpen = 93;
  public static final int strongOpen = 50;
  public static final int ddClose = 170;
  public static final int centerClose = 139;
  public static final int xmpClose = 195;
  public static final int menuClose = 184;
  public static final int htmlOpen = 159;
  public static final int delOpen = 196;
  public static final int multicolOpen = 185;
  public static final int SPACER = 29;
  public static final int objectOpen = 60;
  public static final int bOpen = 130;
  public static final int blinkClose = 65;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "UMINUS",
  "TIMES",
  "LPAREN",
  "RPAREN",
  "NUMBER",
  "IVAL",
  "RVAL",
  "BVAL",
  "BGSOUND",
  "BASE",
  "ISINDEX",
  "LINK",
  "META",
  "NEXTID",
  "styleOpen",
  "styleClose",
  "plainText",
  "scriptOpen",
  "scriptClose",
  "addressOpen",
  "addressClose",
  "EMBED",
  "IFRAME",
  "IMG",
  "SPACER",
  "WBR",
  "PARAM",
  "appletOpen",
  "appletClose",
  "abbrOpen",
  "abbrClose",
  "acronymOpen",
  "acronymClose",
  "citeOpen",
  "citeClose",
  "codeOpen",
  "codeClose",
  "dfnOpen",
  "dfnClose",
  "emOpen",
  "emClose",
  "kbdOpen",
  "kbdClose",
  "qOpen",
  "qClose",
  "strongOpen",
  "strongClose",
  "varOpen",
  "varClose",
  "ilayerOpen",
  "ilayerClose",
  "noembedOpen",
  "noembedClose",
  "noscriptOpen",
  "noscriptClose",
  "objectOpen",
  "objectClose",
  "bdoOpen",
  "bdoClose",
  "blinkOpen",
  "blinkClose",
  "sOpen",
  "sClose",
  "spanOpen",
  "spanClose",
  "strikeOpen",
  "strikeClose",
  "ttOpen",
  "ttClose",
  "marqueeOpen",
  "marqueeClose",
  "basefontOpen",
  "basefontClose",
  "blockquoteOpen",
  "blockquoteClose",
  "dirOpen",
  "dirClose",
  "endTag",
  "bodyOpen",
  "bodyClose",
  "frameOpen",
  "framesetOpen",
  "framesetClose",
  "noframesOpen",
  "noframesClose",
  "formOpen",
  "formClose",
  "input",
  "selectOpen",
  "selectClose",
  "optionOpen",
  "optionClose",
  "tableOpen",
  "tableClose",
  "trOpen",
  "trClose",
  "tdOpen",
  "tdClose",
  "thOpen",
  "thClose",
  "thread",
  "tbody",
  "img",
  "aOpen",
  "aClose",
  "ulOpen",
  "ulClose",
  "liOpen",
  "liClose",
  "olOpen",
  "olClose",
  "pOpen",
  "pClose",
  "iOpen",
  "iClose",
  "uOpen",
  "uClose",
  "colon",
  "comma",
  "semicolon",
  "assign",
  "nobrOpen",
  "bigClose",
  "bigOpen",
  "nobrClose",
  "bOpen",
  "bClose",
  "smallOpen",
  "smallClose",
  "supOpen",
  "supClose",
  "subOpen",
  "subClose",
  "centerOpen",
  "centerClose",
  "fontOpen",
  "fontClose",
  "h1Open",
  "h1Close",
  "h2Open",
  "h2Close",
  "h3Open",
  "h3Close",
  "thead",
  "h4Open",
  "h4Close",
  "h5Open",
  "h5Close",
  "h6Open",
  "h6Close",
  "hr",
  "br",
  "divisionOpen",
  "divisionClose",
  "htmlOpen",
  "htmlClose",
  "headOpen",
  "headClose",
  "titleOpen",
  "titleClose",
  "dlOpen",
  "dlClose",
  "dtOpen",
  "dtClose",
  "ddOpen",
  "ddClose",
  "KEYGEN",
  "fieldsetOpen",
  "fieldsetClose",
  "legendOpen",
  "legendClose",
  "LABEL",
  "textareaOpen",
  "textareaClose",
  "optgroupOpen",
  "optgroupClose",
  "listingOpen",
  "listingClose",
  "menuOpen",
  "menuClose",
  "multicolOpen",
  "multicolClose",
  "preOpen",
  "preClose",
  "captionOpen",
  "captionClose",
  "COLGROUP",
  "COL",
  "tfoot",
  "xmpOpen",
  "xmpClose",
  "delOpen",
  "delClose",
  "insOpen",
  "insClose",
  "layerOpen",
  "layerClose",
  "mapOpen",
  "mapClose",
  "AREA",
  "ID",
  "comment",
  "whitespace"
  };
}

